version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.11.0
    steps:
      - checkout
      - run:
          name: "Say Hello"
          command: "curl --location 'https://public.testgrid.io/api/app-build-run' \
            --form 'user_token='f7fvdxj9421psqou2296u0gjmneofz2t'' \
            --form 'app_build_id='866'' \
            --form 'version_module_id='19138'' \
            --form 'process_type='oaa'' \
            --form 'application_token='81b3e71657a58c54692d93ddcef52691'' \
            --form 'version_token='e646f58ae5b6f34499edb61801230752'' \
            --form 'device_name='Galaxy A34 5G''"
workflows:
  build:
    jobs:
      - build
